import Head from "next/head";
import { TextInputBox } from "@/components/TextInputBox";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pick random cypress tests</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TextInputBox />
      </main>
    </>
  );
}
